name: Build release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.14

      - name: Build binaries
        run: make build_all

      - name: Upload Darwin AMD64
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/web-logbook-darwin-amd64.tar.gz

      - name: Upload Darwin ARM64
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/web-logbook-darwin-arm64.tar.gz

      - name: Upload Linux AMD64
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/web-logbook-linux-amd64.tar.gz

      - name: Upload Linux ARM64
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/web-logbook-linux-arm64.tar.gz

      - name: Upload Linux ARM32
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/web-logbook-linux-arm.tar.gz

      - name: Upload Window AMD64
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/web-logbook-windows-amd64.zip